"""add task entity

Revision ID: fde803933c04
Revises: 5dcca8400b2f
Create Date: 2024-04-06 21:46:17.514721

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fde803933c04"
down_revision: Union[str, None] = "5dcca8400b2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "title", sa.String(length=256), nullable=False
        ),
        sa.Column(
            "description",
            sa.String(length=256),
            nullable=True,
        ),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    # ### end Alembic commands ###
